"""Append-only, hash-chained audit log (ADR-007).

No update or delete path exists through this module — storage only grows.
Each entry's hash covers its own content plus the previous entry's hash, so
`verify_chain()` can detect tampering by recomputing every hash rather than
trusting a status flag (the exact "security theater" pattern the Emergent
audit found — see docs/adr/ADR-007).
"""
from __future__ import annotations

import hashlib
import json
import uuid
from contextvars import ContextVar, Token
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Protocol

from app.kernel.context import current_context

GENESIS_HASH = "0" * 64


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _compute_hash(
    *,
    entry_id: str,
    action: str,
    resource_type: str,
    resource_id: str | None,
    decision: str | None,
    principal_id: str,
    payload: dict,
    created_at: str,
    prev_hash: str,
) -> str:
    canonical = json.dumps(
        {
            "entry_id": entry_id,
            "action": action,
            "resource_type": resource_type,
            "resource_id": resource_id,
            "decision": decision,
            "principal_id": principal_id,
            "payload": payload,
            "created_at": created_at,
            "prev_hash": prev_hash,
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class AuditEntry:
    entry_id: str
    action: str
    resource_type: str
    resource_id: str | None
    decision: str | None
    principal_id: str
    payload: dict
    created_at: str
    prev_hash: str
    hash: str = field(compare=False)

    def recompute_hash(self) -> str:
        return _compute_hash(
            entry_id=self.entry_id,
            action=self.action,
            resource_type=self.resource_type,
            resource_id=self.resource_id,
            decision=self.decision,
            principal_id=self.principal_id,
            payload=self.payload,
            created_at=self.created_at,
            prev_hash=self.prev_hash,
        )


class AuditStore(Protocol):
    async def append(self, entry: AuditEntry) -> None: ...
    async def last_hash(self) -> str: ...
    async def all_entries(self) -> list[AuditEntry]: ...


_store_var: ContextVar[AuditStore | None] = ContextVar("landvault_audit_store", default=None)

# Write-once at startup, read-only afterward — safe as a plain global
# (unlike _store_var, nothing ever mutates this per-request). Backstops
# audit() calls that happen before any per-request session exists, e.g. the
# PEP's authz-deny audit (app.kernel.authorization.pep) runs during
# dependency resolution, before app.kernel.uow.get_db_session is ever
# reached — confirmed against a live server: without this, such a call
# raised "audit store not configured" (RuntimeError -> 500) instead of the
# expected 403.
_eager_fallback: AuditStore | None = None


def configure_eager_fallback(store: AuditStore) -> None:
    global _eager_fallback
    _eager_fallback = store


def configure_audit_store(store: AuditStore) -> Token[AuditStore | None]:
    """A ContextVar, not a plain global: under real concurrent requests
    (each its own asyncio Task), a global would let one request's audit
    store binding stomp another's mid-flight. Production binds this per
    request (app.kernel.uow.get_db_session); tests bind it once per test."""
    return _store_var.set(store)


def reset_audit_store(token: Token[AuditStore | None]) -> None:
    _store_var.reset(token)


def get_audit_store() -> AuditStore:
    store = _store_var.get()
    if store is not None:
        return store
    if _eager_fallback is not None:
        return _eager_fallback
    raise RuntimeError("audit store not configured — call configure_audit_store() at startup")


async def audit(
    action: str,
    *,
    resource_type: str = "unknown",
    resource_id: str | None = None,
    decision: str | None = None,
    payload: dict | None = None,
    entry_id: str | None = None,
) -> AuditEntry:
    """`entry_id`: optional, pre-generated by the caller (docs/adr/ADR-023) —
    lets a caller reference this entry's id (e.g. a history row's
    `audit_ref`) in writes that must commit *before* this call's own,
    independently-durable commit (app.kernel.audit_postgres.
    PostgresAuditStore.append() commits eagerly). Every existing caller
    omits it and gets the prior behavior unchanged."""
    store = get_audit_store()
    ctx = current_context()
    prev_hash = await store.last_hash()
    entry_id = entry_id or uuid.uuid4().hex
    created_at = _now_iso()
    payload = payload or {}
    entry_hash = _compute_hash(
        entry_id=entry_id,
        action=action,
        resource_type=resource_type,
        resource_id=resource_id,
        decision=decision,
        principal_id=ctx.principal_id,
        payload=payload,
        created_at=created_at,
        prev_hash=prev_hash,
    )
    entry = AuditEntry(
        entry_id=entry_id,
        action=action,
        resource_type=resource_type,
        resource_id=resource_id,
        decision=decision,
        principal_id=ctx.principal_id,
        payload=payload,
        created_at=created_at,
        prev_hash=prev_hash,
        hash=entry_hash,
    )
    await store.append(entry)
    return entry


async def verify_chain() -> bool:
    """DAG-aware verifier (ADR-030, GD-010): the audit chain is a hash-linked
    DAG, not a strict single-predecessor line — more than one entry may
    legitimately share a `prev_hash` (including `GENESIS_HASH` itself), which
    is the normal shape of two concurrent writers rather than corruption.
    Validates one fetched snapshot against six invariants: every entry's
    hash recomputes correctly; every non-genesis `prev_hash` resolves to an
    entry in that same snapshot; every entry's predecessor chain terminates
    at `GENESIS_HASH` (reachability) without revisiting an entry already seen
    on that walk (acyclicity); and branching/multiple-genesis-roots verify
    as valid, not invalid. Does not, and cannot, prove complete-history
    inclusion — terminal-leaf, whole-branch, or tail deletion can remain
    undetectable if nothing surviving references what was removed (ADR-030
    §6). Does not manufacture ordering from `created_at`, row identity, or
    insertion position — `prev_hash` is a predecessor/reference relation
    only (ADR-030 §7)."""
    store = get_audit_store()
    entries = await store.all_entries()

    by_hash: dict[str, AuditEntry] = {}
    for entry in entries:
        if entry.hash in by_hash:
            # A real UNIQUE(hash) constraint makes this unreachable against
            # production Postgres (app.kernel.audit_postgres); guarded here
            # so a non-conforming store/fixture can never silently collapse
            # two entries into one and have the reduced graph read as valid.
            return False
        by_hash[entry.hash] = entry

    for entry in entries:
        if entry.recompute_hash() != entry.hash:
            return False

    resolved: dict[str, bool] = {}
    for entry in entries:
        if not _reaches_genesis(entry.hash, by_hash, resolved):
            return False
    return True


def _reaches_genesis(
    start_hash: str, by_hash: dict[str, AuditEntry], resolved: dict[str, bool]
) -> bool:
    """One iterative backward walk from `start_hash` toward `GENESIS_HASH`,
    memoized in `resolved` across calls so the overall verify_chain() cost
    stays ~O(V + E) — each entry's predecessor edge is walked at most once
    across the whole verification pass, however many descendants share it,
    instead of re-walking shared ancestors once per descendant. Combines
    referential validity, reachability, and acyclicity in the single walk
    ADR-030 §2/GD-010 §8 describe: a missing `prev_hash` (referential
    validity) and a revisited entry (acyclicity) are both terminal,
    non-genesis stops that make the whole path invalid; only actually
    reaching `GENESIS_HASH` makes it valid. Iterative, not recursive — a
    long linear history cannot exhaust the call stack."""
    path: list[str] = []
    path_seen: set[str] = set()
    current = start_hash
    while True:
        if current == GENESIS_HASH:
            result = True
            break
        if current in resolved:
            result = resolved[current]
            break
        if current in path_seen:
            result = False  # cycle: revisited an entry already on this walk
            break
        entry = by_hash.get(current)
        if entry is None:
            result = False  # dangling prev_hash: no entry has this hash
            break
        path.append(current)
        path_seen.add(current)
        current = entry.prev_hash

    for node in path:
        resolved[node] = result
    return result
